os: linux
dist: focal
language: python
cache: pip
python:
  - "3.9"
jobs:
  include:
    - stage: test
      cache:
        - pip: true
        - directories:
            - $HOME/.cache/pypoetry
      install:
        - sudo apt-get -y install nodejs
        - npm install -g ganache-cli 
        - pip install poetry
        - poetry config virtualenvs.create false && poetry install -n --no-ansi
        - brownie pm install OpenZeppelin/openzeppelin-contracts@4.2.0
      script:
        - black --check .
        - isort --profile black --check .
        - brownie test

